image:
  repository: sonatype/nexus3
  tag: "3.68.1"
  pullPolicy: IfNotPresent

nexus:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - name: nexus.cybrex.ru
        path: /
    tls:
      - hosts:
          - nexus.cybrex.ru
        secretName: nexus-tls
